vm_types:
- name: basic
  cloud_properties:
    name: machine name
    flavor: L
    rsa_key: ((ssh_key))
    datacenter: ((datacenter))

networks:
- name: default
  type: dynamic
  cloud_properties:
    private-network-id: ((private_network_id))
    firewall-policy-name: default

compilation:
  workers: 2
  network: default
  vm_type: basic
  reuse_compilation_vms: true

